# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CECW' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CECW


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

end

target 'CECW-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CECW-tvOS

end
